// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxJ8aMKdXLn3gs9Zs0yc_4CkU5-kNYcP8',
    appId: '1:980678477813:web:2499995c25fe1cde2b02bc',
    messagingSenderId: '980678477813',
    projectId: 'urchat-a5',
    authDomain: 'urchat-a5.firebaseapp.com',
    storageBucket: 'urchat-a5.firebasestorage.app',
    measurementId: 'G-5MPD2QCXDE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJELy26JibsR48H6oLmTIFXZz65wwLx5g',
    appId: '1:980678477813:android:165e2c07da1cea6b2b02bc',
    messagingSenderId: '980678477813',
    projectId: 'urchat-a5',
    storageBucket: 'urchat-a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtI3aurDZbgM_vgeocVlrjtUGMi1SPdqQ',
    appId: '1:980678477813:ios:b4707cc2124b12dc2b02bc',
    messagingSenderId: '980678477813',
    projectId: 'urchat-a5',
    storageBucket: 'urchat-a5.firebasestorage.app',
    iosBundleId: 'com.exotech.urchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxJ8aMKdXLn3gs9Zs0yc_4CkU5-kNYcP8',
    appId: '1:980678477813:web:1a9e7386197c131c2b02bc',
    messagingSenderId: '980678477813',
    projectId: 'urchat-a5',
    authDomain: 'urchat-a5.firebaseapp.com',
    storageBucket: 'urchat-a5.firebasestorage.app',
    measurementId: 'G-QSB2MBN6NX',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtI3aurDZbgM_vgeocVlrjtUGMi1SPdqQ',
    appId: '1:980678477813:ios:f70970b25d7354912b02bc',
    messagingSenderId: '980678477813',
    projectId: 'urchat-a5',
    storageBucket: 'urchat-a5.firebasestorage.app',
    iosBundleId: 'com.example.urchatBackTesting',
  );

}