import 'package:animated_emoji/animated_emoji.dart';

class AnimatedEmojiMapper {
  static final Map<String, AnimatedEmojiData> _emojiToAnimatedMap = {
    '😀': AnimatedEmojis.smile,
    '😃': AnimatedEmojis.smileWithBigEyes,
    '😄': AnimatedEmojis.grin,
    '😁': AnimatedEmojis.grinning,
    '😆': AnimatedEmojis.laughing,
    '😅': AnimatedEmojis.grinSweat,
    '😂': AnimatedEmojis.joy,
    '🤣': AnimatedEmojis.rofl,
    '😭': AnimatedEmojis.loudlyCrying,
    '😉': AnimatedEmojis.wink,
    '😗': AnimatedEmojis.kissing,
    '😙': AnimatedEmojis.kissingSmilingEyes,
    '😚': AnimatedEmojis.kissingClosedEyes,
    '😘': AnimatedEmojis.kissingHeart,
    '🥰': AnimatedEmojis.heartFace,
    '😍': AnimatedEmojis.heartEyes,
    '🤩': AnimatedEmojis.starStruck,
    '🥳': AnimatedEmojis.partyingFace,
    '🫠': AnimatedEmojis.melting,
    '🙃': AnimatedEmojis.upsideDownFace,
    '🙂': AnimatedEmojis.slightlyHappy,
    '🥲': AnimatedEmojis.happyCry,
    '🫣': AnimatedEmojis.holdingBackTears,
    '😊': AnimatedEmojis.blush,
    '☺️': AnimatedEmojis.warmSmile,
    '😌': AnimatedEmojis.relieved,
    '🙂↕️': AnimatedEmojis.headNod,
    '🙂↔️': AnimatedEmojis.headShake,
    '😏': AnimatedEmojis.smirk,
    '🤤': AnimatedEmojis.drool,
    '😋': AnimatedEmojis.yum,
    '😛': AnimatedEmojis.stuckOutTongue,
    '😜': AnimatedEmojis.squintingTongue,
    '😝': AnimatedEmojis.winkyTongue,
    '🤪': AnimatedEmojis.zanyFace,
    '🥴': AnimatedEmojis.woozy,
    '😔': AnimatedEmojis.pensive,
    '🥺': AnimatedEmojis.pleading,
    '😬': AnimatedEmojis.grimacing,
    '😑': AnimatedEmojis.expressionless,
    '😐': AnimatedEmojis.neutralFace,
    '😶': AnimatedEmojis.mouthNone,
    '😶‍🌫️': AnimatedEmojis.faceInClouds,
    '🫥': AnimatedEmojis.dottedLineFace,
    '🤐': AnimatedEmojis.zipperFace,
    '🫡': AnimatedEmojis.salute,
    '🤔': AnimatedEmojis.thinkingFace,
    '🤫': AnimatedEmojis.shushingFace,
    '🫢': AnimatedEmojis.handOverMouth,
    '🤭': AnimatedEmojis.smilingEyesWithHandOverMouth,
    '🥱': AnimatedEmojis.yawn,
    '🤗': AnimatedEmojis.hugFace,
    '🫣': AnimatedEmojis.peeking,
    '😱': AnimatedEmojis.screaming,
    '🤨': AnimatedEmojis.raisedEyebrow,
    '🧐': AnimatedEmojis.monocle,
    '😒': AnimatedEmojis.unamused,
    '🙄': AnimatedEmojis.rollingEyes,
    '😮‍💨': AnimatedEmojis.exhale,
    '😤': AnimatedEmojis.triumph,
    '😠': AnimatedEmojis.angry,
    '😡': AnimatedEmojis.rage,
    '🤬': AnimatedEmojis.cursing,
    '😞': AnimatedEmojis.sad,
    '😓': AnimatedEmojis.sweat,
    '😟': AnimatedEmojis.worried,
    '😥': AnimatedEmojis.concerned,
    '😢': AnimatedEmojis.cry,
    '☹️': AnimatedEmojis.bigFrown,
    '🙁': AnimatedEmojis.frown,
    '🫤': AnimatedEmojis.diagonalMouth,
    '😕': AnimatedEmojis.slightlyFrowning,
    '😰': AnimatedEmojis.anxiousWithSweat,
    '😨': AnimatedEmojis.scared,
    '😧': AnimatedEmojis.anguished,
    '😦': AnimatedEmojis.gasp,
    '😮': AnimatedEmojis.mouthOpen,
    '😯': AnimatedEmojis.surprised,
    '😲': AnimatedEmojis.astonished,
    '😳': AnimatedEmojis.flushed,
    '🤯': AnimatedEmojis.mindBlown,
    '😖': AnimatedEmojis.scrunchedMouth,
    '😣': AnimatedEmojis.scrunchedEyes,
    '😩': AnimatedEmojis.weary,
    '😫': AnimatedEmojis.distraught,
    '😵': AnimatedEmojis.xEyes,
    '😵‍💫': AnimatedEmojis.dizzyFace,
    '🫨': AnimatedEmojis.shakingFace,
    '🥶': AnimatedEmojis.coldFace,
    '🥵': AnimatedEmojis.hotFace,
    '🤢': AnimatedEmojis.sick,
    '🤮': AnimatedEmojis.vomit,
    '🫨': AnimatedEmojis.tired,
    '😴': AnimatedEmojis.sleep,
    '😪': AnimatedEmojis.sleepy,
    '🤧': AnimatedEmojis.sneeze,
    '🤒': AnimatedEmojis.thermometerFace,
    '🤕': AnimatedEmojis.bandageFace,
    '😷': AnimatedEmojis.mask,
    '🤥': AnimatedEmojis.liar,
    '😇': AnimatedEmojis.halo,
    '🤠': AnimatedEmojis.cowboy,
    '🤑': AnimatedEmojis.moneyFace,
    '🤓': AnimatedEmojis.nerdFace,
    '😎': AnimatedEmojis.sunglassesFace,
    '🥸': AnimatedEmojis.disguise,
    '🤡': AnimatedEmojis.clown,
    '💩': AnimatedEmojis.poop,
    '😈': AnimatedEmojis.impSmile,
    '👿': AnimatedEmojis.impFrown,
    '👻': AnimatedEmojis.ghost,
    '💀': AnimatedEmojis.skull,
    '☃️': AnimatedEmojis.snowmanWithSnow,
    '⛄': AnimatedEmojis.snowman,
    '🎃': AnimatedEmojis.jackOLantern,
    '🤖': AnimatedEmojis.robot,
    '👽': AnimatedEmojis.alien,
    '👾': AnimatedEmojis.alienMonster,
    '🌞': AnimatedEmojis.sunWithFace,
    '🌛': AnimatedEmojis.moonFaceFirstQuarter,
    '🌜': AnimatedEmojis.moonFaceLastQuarter,
    '😺': AnimatedEmojis.smileyCat,
    '😸': AnimatedEmojis.smileCat,
    '😹': AnimatedEmojis.joyCat,
    '😻': AnimatedEmojis.heartEyesCat,
    '😼': AnimatedEmojis.smirkCat,
    '😽': AnimatedEmojis.kissingCat,
    '🙀': AnimatedEmojis.screamCat,
    '😿': AnimatedEmojis.cryingCatFace,
    '😾': AnimatedEmojis.poutingCat,
    '🙈': AnimatedEmojis.seeNoEvilMonkey,
    '🙉': AnimatedEmojis.hearNoEvilMonkey,
    '🙊': AnimatedEmojis.speakNoEvilMonkey,
    '🌟': AnimatedEmojis.glowingStar,
    '✨': AnimatedEmojis.sparkles,
    '⚡': AnimatedEmojis.electricity,
    '💥': AnimatedEmojis.collision,
    '🔥': AnimatedEmojis.fire,
    '💯': AnimatedEmojis.oneHundred,
    '🎉': AnimatedEmojis.partyPopper,
    '🎊': AnimatedEmojis.confettiBall,
    '❤️': AnimatedEmojis.redHeart,
    '🧡': AnimatedEmojis.orangeHeart,
    '💛': AnimatedEmojis.yellowHeart,
    '💚': AnimatedEmojis.greenHeart,
    '🩵': AnimatedEmojis.lightBlueHeart,
    '💙': AnimatedEmojis.blueHeart,
    '💜': AnimatedEmojis.purpleHeart,
    '🤎': AnimatedEmojis.brownHeart,
    '🖤': AnimatedEmojis.blackHeart,
    '🩶': AnimatedEmojis.greyHeart,
    '🤍': AnimatedEmojis.whiteHeart,
    '🩷': AnimatedEmojis.pinkHeart,
    '💘': AnimatedEmojis.cupid,
    '💝': AnimatedEmojis.giftHeart,
    '💖': AnimatedEmojis.sparklingHeart,
    '💗': AnimatedEmojis.heartGrow,
    '💓': AnimatedEmojis.beatingHeart,
    '💞': AnimatedEmojis.revolvingHearts,
    '💕': AnimatedEmojis.twoHearts,
    '💌': AnimatedEmojis.loveLetter,
    '💟': AnimatedEmojis.heartBox,
    '❣️': AnimatedEmojis.heartExclamationPoint,
    '🩹': AnimatedEmojis.bandagedHeart,
    '💔': AnimatedEmojis.brokenHeart,
    '❤️‍🔥': AnimatedEmojis.fireHeart,
    '💋': AnimatedEmojis.kiss,
    '👣': AnimatedEmojis.footprints,
    '🫰': AnimatedEmojis.fingerprint,
    '🫀': AnimatedEmojis.anatomicalHeart,
    '🩸': AnimatedEmojis.blood,
    '🦠': AnimatedEmojis.microbe,
    '👀': AnimatedEmojis.eyes,
    '👁️': AnimatedEmojis.eye,
    '🫦': AnimatedEmojis.bitingLip,
    '👃': AnimatedEmojis.nose,
    '👂': AnimatedEmojis.ear,
    '🦻': AnimatedEmojis.hearingAid,
    '🦶': AnimatedEmojis.foot,
    '🦵': AnimatedEmojis.leg,
    '🦼': AnimatedEmojis.legMechanical,
    '🦾': AnimatedEmojis.armMechanical,
    '💪': AnimatedEmojis.muscle,
    '👏': AnimatedEmojis.clap,
    '👍': AnimatedEmojis.thumbsUp,
    '👎': AnimatedEmojis.thumbsDown,
    '🫶': AnimatedEmojis.heartHands,
    '🙌': AnimatedEmojis.raisingHands,
    '👐': AnimatedEmojis.openHands,
    '🤲': AnimatedEmojis.palmsUp,
    '🤞': AnimatedEmojis.fistRightwards,
    '🤙': AnimatedEmojis.fistLeftwards,
    '✊': AnimatedEmojis.raisedFist,
    '👊': AnimatedEmojis.fist,
    '🫳': AnimatedEmojis.palmDown,
    '🫴': AnimatedEmojis.palmUp,
    '🫱': AnimatedEmojis.rightwardsHand,
    '🫲': AnimatedEmojis.leftwardsHand,
    '🫸': AnimatedEmojis.pushRightwards,
    '🫷': AnimatedEmojis.pushLeftwards,
    '👋': AnimatedEmojis.wave,
    '🤚': AnimatedEmojis.backHand,
    '🖐️': AnimatedEmojis.palm,
    '✋': AnimatedEmojis.raisedHand,
    '🖖': AnimatedEmojis.vulcan,
    '🤘': AnimatedEmojis.metal,
    '✌️': AnimatedEmojis.victory,
    '🤞': AnimatedEmojis.crossedFingers,
    '🫰': AnimatedEmojis.handWithIndexFingerAndThumbCrossed,
    '🤙': AnimatedEmojis.callMeHand,
    '🤌': AnimatedEmojis.pinchedFingers,
    '🤏': AnimatedEmojis.pinch,
    '👌': AnimatedEmojis.ok,
    '🫵': AnimatedEmojis.pointing,
    '👉': AnimatedEmojis.pointRight,
    '👈': AnimatedEmojis.pointLeft,
    '☝️': AnimatedEmojis.indexFinger,
    '👆': AnimatedEmojis.pointUp,
    '👇': AnimatedEmojis.pointDown,
    '🖕': AnimatedEmojis.middleFinger,
    '✍️': AnimatedEmojis.writingHand,
    '🤳': AnimatedEmojis.selfie,
    '🙏': AnimatedEmojis.foldedHands,
    '💅': AnimatedEmojis.nailCare,
    '🤝': AnimatedEmojis.handshake,
    '💃': AnimatedEmojis.dancerWoman,
    '💐': AnimatedEmojis.bouquet,
    '🌹': AnimatedEmojis.rose,
    '🥀': AnimatedEmojis.wiltedFlower,
    '🍂': AnimatedEmojis.fallenLeaf,
    '🌱': AnimatedEmojis.plant,
    '🍃': AnimatedEmojis.leaves,
    '🍀': AnimatedEmojis.luck,
    '🪹': AnimatedEmojis.leaflessTree,
    '❄️': AnimatedEmojis.snowflake,
    '🌋': AnimatedEmojis.volcano,
    '🌅': AnimatedEmojis.sunrise,
    '🌄': AnimatedEmojis.sunriseOverMountains,
    '🌈': AnimatedEmojis.rainbow,
    '🫧': AnimatedEmojis.bubbles,
    '🌊': AnimatedEmojis.ocean,
    '🌬️': AnimatedEmojis.windFace,
    '🌪️': AnimatedEmojis.tornado,
    '💧': AnimatedEmojis.droplet,
    '🌧️': AnimatedEmojis.rainCloud,
    '🌩️': AnimatedEmojis.cloudWithLightning,
    '🌍': AnimatedEmojis.globeShowingEuropeAfrica,
    '🌎': AnimatedEmojis.globeShowingAmericas,
    '🌏': AnimatedEmojis.globeShowingAsiaAustralia,
    '☄️': AnimatedEmojis.comet,
    '🐮': AnimatedEmojis.cowFace,
    '🦄': AnimatedEmojis.unicorn,
    '🦎': AnimatedEmojis.lizard,
    '🐉': AnimatedEmojis.dragon,
    '🦖': AnimatedEmojis.tRex,
    '🦕': AnimatedEmojis.dinosaur,
    '🐢': AnimatedEmojis.turtle,
    '🐊': AnimatedEmojis.crocodile,
    '🐍': AnimatedEmojis.snake,
    '🐸': AnimatedEmojis.frog,
    '🐇': AnimatedEmojis.rabbit,
    '🐀': AnimatedEmojis.rat,
    '🐩': AnimatedEmojis.poodle,
    '🐕': AnimatedEmojis.dog,
    '🦮': AnimatedEmojis.guideDog,
    '🐕‍🦺': AnimatedEmojis.serviceDog,
    '🐖': AnimatedEmojis.pig,
    '🐎': AnimatedEmojis.racehorse,
    '🫏': AnimatedEmojis.donkey,
    '🐂': AnimatedEmojis.ox,
    '🐐': AnimatedEmojis.goat,
    '🦘': AnimatedEmojis.kangaroo,
    '🐅': AnimatedEmojis.tiger,
    '🐒': AnimatedEmojis.monkey,
    '🦍': AnimatedEmojis.gorilla,
    '🦧': AnimatedEmojis.orangutan,
    '🐿️': AnimatedEmojis.chipmunk,
    '🦦': AnimatedEmojis.otter,
    '🦇': AnimatedEmojis.bat,
    '🐦': AnimatedEmojis.bird,
    '🐦‍⬛': AnimatedEmojis.blackBird,
    '🐓': AnimatedEmojis.rooster,
    '🐣': AnimatedEmojis.hatchingChick,
    '🐤': AnimatedEmojis.babyChick,
    '🐥': AnimatedEmojis.hatchedChick,
    '🦅': AnimatedEmojis.eagle,
    '🦉': AnimatedEmojis.owl,
    '🕊️': AnimatedEmojis.peace,
    '🪿': AnimatedEmojis.goose,
    '🦚': AnimatedEmojis.peacock,
    '🐦‍🔥': AnimatedEmojis.phoenix,
    '🦭': AnimatedEmojis.seal,
    '🦈': AnimatedEmojis.shark,
    '🐬': AnimatedEmojis.dolphin,
    '🐋': AnimatedEmojis.whale,
    '🐟': AnimatedEmojis.fish,
    '🐡': AnimatedEmojis.blowfish,
    '🦞': AnimatedEmojis.lobster,
    '🦀': AnimatedEmojis.crab,
    '🐙': AnimatedEmojis.octopus,
    '🪼': AnimatedEmojis.jellyfish,
    '🦂': AnimatedEmojis.scorpion,
    '🕷️': AnimatedEmojis.spider,
    '🐌': AnimatedEmojis.snail,
    '🐜': AnimatedEmojis.ant,
    '🦟': AnimatedEmojis.mosquito,
    '🪳': AnimatedEmojis.cockroach,
    '🪰': AnimatedEmojis.fly,
    '🐝': AnimatedEmojis.bee,
    '🐞': AnimatedEmojis.ladyBug,
    '🦋': AnimatedEmojis.butterfly,
    '🐛': AnimatedEmojis.bug,
    '🪱': AnimatedEmojis.worm,
    '🐾': AnimatedEmojis.pawPrints,
    '🍅': AnimatedEmojis.tomato,
    '🫚': AnimatedEmojis.rootVegetable,
    '🍳': AnimatedEmojis.cooking,
    '🌯': AnimatedEmojis.burrito,
    '🍝': AnimatedEmojis.spaghetti,
    '🍜': AnimatedEmojis.steamingBowl,
    '🍿': AnimatedEmojis.popcorn,
    '☕': AnimatedEmojis.hotBeverage,
    '🍻': AnimatedEmojis.clinkingBeerMugs,
    '🥂': AnimatedEmojis.clinkingGlasses,
    '🍾': AnimatedEmojis.bottleWithPoppingCork,
    '🍷': AnimatedEmojis.wineGlass,
    '🫗': AnimatedEmojis.pour,
    '🍹': AnimatedEmojis.tropicalDrink,
    '🚧': AnimatedEmojis.construction,
    '🚨': AnimatedEmojis.policeCarLight,
    '🚲': AnimatedEmojis.bicycle,
    '🚗': AnimatedEmojis.automobile,
    '🏎️': AnimatedEmojis.racingCar,
    '🚕': AnimatedEmojis.taxi,
    '🚌': AnimatedEmojis.bus,
    '⛵': AnimatedEmojis.sailboat,
    '🛶': AnimatedEmojis.canoe,
    '🛸': AnimatedEmojis.flyingSaucer,
    '🚀': AnimatedEmojis.rocket,
    '🛫': AnimatedEmojis.airplaneDeparture,
    '🛬': AnimatedEmojis.airplaneArrival,
    '🎢': AnimatedEmojis.rollerCoaster,
    '🎡': AnimatedEmojis.ferrisWheel,
    '🏕️': AnimatedEmojis.camping,
    '🎈': AnimatedEmojis.balloon,
    '🎂': AnimatedEmojis.birthdayCake,
    '🎁': AnimatedEmojis.wrappedGift,
    '🎆': AnimatedEmojis.fireworks,
    '🪅': AnimatedEmojis.pinata,
    '🪩': AnimatedEmojis.mirrorBall,
    '🥇': AnimatedEmojis.goldMedal,
    '🥈': AnimatedEmojis.silverMedal,
    '🥉': AnimatedEmojis.bronzeMedal,
    '🏆': AnimatedEmojis.trophy,
    '⚽': AnimatedEmojis.soccerBall,
    '⚾': AnimatedEmojis.baseball,
    '🥎': AnimatedEmojis.softball,
    '🎾': AnimatedEmojis.tennis,
    '🏸': AnimatedEmojis.badminton,
    '🥍': AnimatedEmojis.lacrosse,
    '🏏': AnimatedEmojis.cricketGame,
    '🏑': AnimatedEmojis.fieldHockey,
    '🏒': AnimatedEmojis.iceHockey,
    '⛸️': AnimatedEmojis.iceSkate,
    '🛼': AnimatedEmojis.rollerSkates,
    '🩰': AnimatedEmojis.balletShoes,
    '🛹': AnimatedEmojis.skateboard,
    '⛳': AnimatedEmojis.flagInHole,
    '🎯': AnimatedEmojis.directHit,
    '🥏': AnimatedEmojis.flyingDisc,
    '🪃': AnimatedEmojis.boomerang,
    '🪁': AnimatedEmojis.kite,
    '🎣': AnimatedEmojis.fishingPole,
    '🥋': AnimatedEmojis.martialArtsUniform,
    '🎱': AnimatedEmojis.eightBall,
    '🏓': AnimatedEmojis.pingPong,
    '🎳': AnimatedEmojis.bowling,
    '🎲': AnimatedEmojis.die,
    '🎰': AnimatedEmojis.slotMachine,
    '🪄': AnimatedEmojis.wand,
  };

  /// Get the animated emoji data for a given emoji string
  static AnimatedEmojiData? getAnimatedEmoji(String emoji) {
    return _emojiToAnimatedMap[emoji];
  }

  /// Get the animated emoji widget for a given emoji string
  static AnimatedEmoji? getAnimatedEmojiWidget(String emoji, {double? size}) {
    final data = getAnimatedEmoji(emoji);
    if (data != null) {
      return AnimatedEmoji(data, size: size);
    }
    return null;
  }

  /// Check if an emoji has an animated version available
  static bool hasAnimatedVersion(String emoji) {
    return _emojiToAnimatedMap.containsKey(emoji);
  }

  /// Get all available emojis that have animated versions
  static List<String> getAvailableEmojis() {
    return _emojiToAnimatedMap.keys.toList();
  }
}

class AnimatedEmojiMapperWithSkinTones extends AnimatedEmojiMapper {
  /// Get animated emoji with skin tone support
  static AnimatedEmojiData? getAnimatedEmojiWithTone(String emoji,
      {EmojiSkinTone? tone}) {
    final baseData = AnimatedEmojiMapper.getAnimatedEmoji(emoji);

    if (baseData != null &&
        tone != null &&
        baseData is AnimatedTonedEmojiData) {
      // Handle skin tone variations
      switch (tone) {
        case EmojiSkinTone.light:
          return baseData.light;
        case EmojiSkinTone.mediumLight:
          return baseData.mediumLight;
        case EmojiSkinTone.medium:
          return baseData.medium;
        case EmojiSkinTone.mediumDark:
          return baseData.mediumDark;
        case EmojiSkinTone.dark:
          return baseData.dark;
        default:
          return baseData;
      }
    }

    return baseData;
  }
}

// Define skin tone enum if not already available
enum EmojiSkinTone {
  light,
  mediumLight,
  medium,
  mediumDark,
  dark,
}
